services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-data:/mosquitto/data
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
    networks:
      - transport_network

  web:
    build:
      context: .
      dockerfile: "Transportation_System/Dockerfile"
    ports:
      - "8081:8080"
    networks:
      - transport_network
    environment:
      - MqttSettings__BrokerAddress
      - ConnectionStrings__DefaultConnection
    depends_on:
      mosquitto:
        condition: service_started
      postgres:
        condition: service_started

  postgres:
    image: postgres:17
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=ABC123
       - POSTGRES_DB=transportationDb
    ports:
      - "54325:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - transport_network

volumes:
  postgres-data: { }
  mosquitto-data:
    
networks:
  transport_network:
    driver: bridge
    name: transport_net
    
