services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-data:/mosquitto/data
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
    networks:
      - transport_network

  valhalla:
    image: ghcr.io/valhalla/valhalla-scripted:latest
    ports:
      - "8002:8002"
    volumes:
      - valhalla-data:/custom_files
    environment:
      - tile_urls=https://download.geofabrik.de/russia/volga-fed-district-latest.osm.pbf
      - build_elevation=False
      - build_admins=True
      - build_time_zones=True
      - force_rebuild=False
      - server_threads=2
    restart: unless-stopped
    networks:
      - transport_network
  
  simulator:
    build:
      context: .
      dockerfile: "Simulator/Dockerfile"
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
      - PUBLISH_INTERVAL_SECONDS=3
      - DEVICE_REFRESH_INTERVAL_SECONDS=30
      - ConnectionStrings__DefaultConnection
    depends_on:
      mosquitto:
        condition: service_started
      postgres:
        condition: service_started
    restart: unless-stopped
    networks:
      - transport_network

  web:
    build:
      context: .
      dockerfile: "Transportation_System/Dockerfile"
    ports:
      - "8081:8080"
    networks:
      - transport_network
    environment:
      - MqttSettings__BrokerAddress
      - ConnectionStrings__DefaultConnection
      - ValhallaSettings__BaseUrl=http://valhalla:8002
    depends_on:
      mosquitto:
        condition: service_started
      postgres:
        condition: service_started
      valhalla:
        condition: service_started

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ABC123
      - POSTGRES_DB=transportationDb
    ports:
      - "54325:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - transport_network

volumes:
  postgres-data: { }
  mosquitto-data: { }
  valhalla-data: { }

networks:
  transport_network:
    driver: bridge
    name: transport_net
    
